### ISSUE TITLE
Parser not working with ublox NEO-6M

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-NMEA-Parser#9]
Hi @aentinger 
I tried the parser with an ublox NEO-6M receiver but unfortunately it didn't work. It seems like GPRMC dataset is formatted a little bit different than expected. Here is a dataset:
$GPRMC,193517.00,A,4837.99895,N,01301.58584,E,0.793,,111020,,,A*7D

Could you have a look on this? Thank you.

**Comment by aentinger** [comment]
Good morning @generationmake :wave: :coffee: 
This is most likely because it contains 4 additional fields: **date**, **mv**, **mvE**, **mode** (see [datasheet](https://www.u-blox.com/en/ubx-viewer/view/u-blox6_ReceiverDescrProtSpec_(GPS.G6-SW-10018)_Public?url=https%3A%2F%2Fwww.u-blox.com%2Fsites%2Fdefault%2Ffiles%2Fproducts%2Fdocuments%2Fu-blox6_ReceiverDescrProtSpec_%2528GPS.G6-SW-10018%2529_Public.pdf) page 63). I'll look into it.

**Comment by aentinger** [comment]
[107-Arduino-NMEA-Parser:1.0.2](https://github.com/107-systems/107-Arduino-NMEA-Parser/releases/tag/1.0.2) has been released. @generationmake can you please test with your ublox GPS module?
